osd-bar=no
border=no

hwdec=auto
vo=gpu-next
gpu-context=wayland

# Font
osd-font='JetBrainsMono Nerd Font'

# Subtitle
sub-scale=0.6

# Play video from last position
save-position-on-quit=yes

# Cache
cache=yes
demuxer-max-bytes=2000M
demuxer-max-back-bytes=500M
