context.modules = [
  { name = libpipewire-module-combine-stream
    args = {
      combine.mode = sink
      node.name = "virtual_combine_all_sinks"
      node.description = "All Outputs Combined"
      combine.latency-compensate = false
      combine.props = {
        audio.position = [ FL FR ]
      }
      stream.props = { }
      stream.rules = [
        { matches = [ { media.class = "Audio/Sink" } ]
          actions = { create-stream = { } }
        }
      ]
    }
  }
]
